### ISSUE TITLE
KeyError: 'COLOR_PARAM' in Line 532

### ISSUE THREAD

**Issue by RexScratch** [jahunsbe1/sb3tosb2#7]
Traceback:
```
Traceback (most recent call last):
  File "SbC3.py", line 596, in <module>
    main(sb3_path, sb2_path, specmap_path, overwrite, debug)
  File "SbC3.py", line 27, in main
    sb2, filemap = project.convert()
  File "SbC3.py", line 193, in convert
    object = self.parseTarget(target)
  File "SbC3.py", line 271, in parseTarget
    script = self.parseScript(id, target["blocks"])
  File "SbC3.py", line 532, in parseScript
    value = blocks[value]["fields"][arg[1]][0]
KeyError: 'COLOR_PARAM'
```

**Comment by BirdLogics** [comment]
This should be fixed now.
